# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/pantho/Videos/Tutorial1/Tutorial1.cache/wt [current_project]
set_property parent.project_path /home/pantho/Videos/Tutorial1/Tutorial1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/pantho/Videos/Tutorial1/Tutorial1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /home/pantho/Videos/Tutorial1/Tutorial1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib {
  /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/imports/Downloads/vga_controller.vhd
  /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
  /home/pantho/Videos/Tutorial1/Tutorial1.srcs/sources_1/new/top_module.vhd
}
read_xdc /home/pantho/Videos/Tutorial1/Tutorial1.srcs/constrs_1/imports/Tutorial1/ZYBO_Master.xdc
set_property used_in_implementation false [get_files /home/pantho/Videos/Tutorial1/Tutorial1.srcs/constrs_1/imports/Tutorial1/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top_module -part xc7z010clg400-1
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
