webtalk_init -webtalk_dir /home/pantho/Videos/Tutorial1/Tutorial1.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 3 16:10:11 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1l4bdsel39201rmfbq5478vq0s" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_13" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1478206850000" -context "sdk\\\\hardware/1478206850000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1478206850000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1478206850000"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4_AR65982" -context "sdk\\\\hardware/1478206850000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1478206850000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1478206850000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1478206850000"
webtalk_add_data -client sdk -key uid -value "1478207068000" -context "sdk\\\\bsp/1478207068000"
webtalk_add_data -client sdk -key hwid -value "1478206850000" -context "sdk\\\\bsp/1478207068000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1478207068000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1478207068000"
webtalk_add_data -client sdk -key uid -value "1478207073000" -context "sdk\\\\application/1478207073000"
webtalk_add_data -client sdk -key hwid -value "1478206850000" -context "sdk\\\\application/1478207073000"
webtalk_add_data -client sdk -key bspid -value "1478207068000" -context "sdk\\\\application/1478207073000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1478207073000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1478207073000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1478207073000"
webtalk_transmit -clientid 2073678871 -regid "" -xml /home/pantho/Videos/Tutorial1/Tutorial1.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/pantho/Videos/Tutorial1/Tutorial1.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/pantho/Videos/Tutorial1/Tutorial1.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
